[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4caf81"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"
